<?php
return [
    // da gigi 
    [
        'restaurant_id' => '2',
        'name' => 'Tagliatelle al ragù',
        'image' => 'Da-gigi\piatto1.jpg',
        'description' => '
        Le tagliatelle al ragù sono una deliziosa combinazione di pasta fresca tagliata a fettuccine e una salsa densa e saporita a base di carne macinata, pomodoro e aromi, che si sposano perfettamente per creare un piatto ricco e appagante, simbolo della cucina italiana.',
        'price' => 15.50,
        'visible' => true,
        'ingredients_list' => 'Tagliatelle fresche o secche,
        Carne macinata ,
        Cipolla,
        Carota,
        Sedano,
        Concentrato di pomodoro,
        Passata di pomodoro,
        Vino rosso,
        Olio evo,
        Sale e pepe,
        Origano,
        Basilico,
        Brodo ',
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Antipasto di salumi misti',
        'image' => 'Da-gigi\piatto2.jpg',
        'description' => 'Un antipasto di salumi misti è un\'esplosione di sapori e tradizione italiana, con una selezione di salumi come prosciutto crudo, salame, coppa e pancetta affettati finemente e disposti in un elegante piatto. Accompagnato da pane croccante e condimenti come sottaceti e olive, è un inizio perfetto per un pasto ricco e conviviale.',
        'price' => 10.50,
        'visible' => true,
        'ingredients_list' => 'salumi del giorno, olive, pomodorini, salsa speciale ',
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Tagliata di bovino adulto',
        'image' => 'Da-gigi\piatto3.jpg',
        'description' => '
        La tagliata di manzo è un piatto succulento e gustoso, composto da fette di carne di manzo grigliate alla perfezione e tagliate a strisce sottili. Servita su un letto di rucola fresca, condita con olio extravergine di oliva, sale marino e scaglie di parmigiano reggiano, è un\'esperienza culinaria indimenticabile che esalta i sapori della carne.',
        'price' => 18.50,
        'visible' => true,
        'ingredients_list' => 'controfiletto di manzo, insalata rucola, pomodorini',
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Grigliata Mista di carne con verdure di stagione',
        'image' => 'Da-gigi\piatto4.jpg',
        'description' => 'Una grigliata di carne e verdure è un festa per i sensi, con gustose bistecche di manzo, salsicce succulente e pollo marinato, abbinati a una varietà di verdure colorate come peperoni, zucchine e melanzane, tutte grigliate alla perfezione e condite con erbe aromatiche e olio d\'oliva extravergine. Un piatto che celebra la freschezza e la semplicità dei sapori della natura.',
        'price' => 35.50,
        'visible' => true,
        'ingredients_list' => 'bistecche, spiedini, salsiccie, zucchine, peperoni',
    ],
    [
        'restaurant_id' => '2',
        'name' => 'Tagliere per aperitivo',
        'image' => 'Da-gigi\piatto5.jpg',
        'description' => 'Un tagliere per aperitivo abbondante è una festa per il palato, con una varietà di salumi prelibati come prosciutto crudo, salame e coppa, formaggi assortiti come pecorino e gorgonzola, accompagnati da olive, sottaceti, frutta secca e pane croccante, offrendo un\'esperienza culinaria ricca e appagante da condividere con gli amici.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
    // mama sushi 
    [
        'restaurant_id' => '4',
        'name' => 'Involtini primavera',
        'image' => 'mamma-sushi\piatto1.jpg',
        'description' => '
        Spring rolls are crispy bite-sized rolls filled with vegetables and meat, perfect for dipping in sweet and sour sauce.',
        'price' => 3.50,
        'visible' => true,
        'ingredients_list' => 'phyllo dough, cabbage, shrimp',
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Poke Bowl',
        'image' => 'mamma-sushi\piatto2.jpg',
        'description' => 'The poke bowl is a fresh and colorful salad of marinated raw fish, served on sushi rice with a variety of toppings like avocado, edamame, and teriyaki sauce.',
        'price' => 10.50,
        'visible' => true,
        'ingredients_list' => 'rice, salmon, tuna, avocado, edamame, seaweed, sesame',
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Tempura di gamberi',
        'image' => 'mamma-sushi\piatto3.jpg',
        'description' => 'Shrimp tempura is a Japanese delicacy: shrimp wrapped in a light and crispy batter, fried to achieve a perfect golden brown, offering a delightful contrast between the outer crispiness and the inner softness of the shrimp.',
        'price' => 8.50,
        'visible' => true,
        'ingredients_list' => 'shrimp, batter',
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Cheesecake al matcha',
        'image' => 'mamma-sushi\piatto4.jpg',
        'description' => 'Matcha cheesecake is a delicate and enveloping Japanese dessert, enriched by the herbal note of matcha tea.',
        'price' => 20.50,
        'visible' => true,
        'ingredients_list' => 'cheese, cake, matcha',
    ],
    [
        'restaurant_id' => '4',
        'name' => 'Barca di sushi misto',
        'image' => 'mamma-sushi\piatto5.jpg',
        'description' => 'The mixed sushi platter offers a selection of Japanese delicacies, including nigiri, maki, and sashimi, for a unique and satisfying combination of flavors and textures.',
        'price' => 1000.50,
        'visible' => true,
        'ingredients_list' => 'a lot of stuff',
    ],
    // red shrimp 
    [
        'restaurant_id' => '1',
        'name' => 'Gambero rosso crudo',
        'image' => 'Red-Shrimp\piatto1.jpg',
        'description' => 'Fresh red prawns served raw, showcasing their natural flavors and delicate texture.',
        'price' => 10.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Gamberi grigliati con verdure',
        'image' => 'Red-Shrimp\piatto2.jpg',
        'description' => 'Grilled shrimp with vegetables: Succulent shrimp grilled to perfection, accompanied by a medley of grilled vegetables for a delicious and healthy dish.',
        'price' => 20.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Guazzetto di gamberi',
        'image' => 'Red-Shrimp\piatto3.jpg',
        'description' => 'A shrimp stew is a savory seafood dish made by simmering shrimp in a flavorful broth with tomatoes, garlic, onions, herbs, and spices, resulting in a rich and aromatic delicacy.',
        'price' => 15.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Paella con gambero gigante',
        'image' => 'Red-Shrimp\piatto4.jpg',
        'description' => 'Paella with king prawns: A traditional Spanish rice dish cooked with flavorful broth, saffron, and an assortment of seafood including large king prawns, creating a rich and aromatic meal.',
        'price' => 20.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
    [
        'restaurant_id' => '1',
        'name' => 'Cruditè di gamberi',
        'image' => 'Red-Shrimp\piatto5.jpg',
        'description' => 'Shrimp crudité: Fresh shrimp served raw as a refreshing appetizer, often accompanied by dipping sauces or dressings for added flavor.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
    // TEXXN
    [
        'restaurant_id' => '3',
        'name' => 'Fritto misto di mare',
        'image' => 'TEXXN\piatto1.jpg',
        'description' => 'A delightful assortment of fried seafood, including shrimp, calamari, and fish, served golden and crispy alongside dipping sauces.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'Calamari, shrimp, vegetables',
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Medaglione di vitello',
        'image' => 'TEXXN\piatto2.jpg',
        'description' => ' Tender cuts of veal, seared to perfection and served with a savory sauce, often accompanied by vegetables or potatoes.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'Veal, vegetables',
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Croissant con burger di manzo',
        'image' => 'TEXXN\piatto3.jpg',
        'description' => 'A unique twist on the classic burger, featuring a juicy beef patty sandwiched between buttery croissant halves, topped with cheese, lettuce, tomato, and condiments.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'croissant, burger, cheddar, salad, tomato',
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Fajitas con pulled chicken',
        'image' => 'TEXXN\piatto4.jpg',
        'description' => ' Flavorful pulled chicken cooked with onions, bell peppers, and spices, served sizzling on a hot skillet alongside warm tortillas, guacamole, sour cream, and salsa for a delicious Tex-Mex meal.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'Chicken, tortilla, sauces, cheese',
    ],
    [
        'restaurant_id' => '3',
        'name' => 'Dolce della casa',
        'image' => 'TEXXN\piatto5.jpg',
        'description' => 'A special homemade dessert, crafted with care by the chef, offering a sweet and indulgent finale to the meal.',
        'price' => 100.50,
        'visible' => true,
        'ingredients_list' => 'un botto di roba',
    ],
];

       